import type { Metadata } from "next";
import "./globals.css";
import Theme from "@/components/theme";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className="container p-4">
        <Theme attribute="class" defaultTheme="dark">
          {children}
        </Theme>
      </body>
    </html>
  );
}
